### ISSUE TITLE
Optional won't work as expected

### ISSUE THREAD

**Issue by vptill** [jamauro/easy-schema#5]
Hello!

I am trying to make your package work after migrating away first from jagi, then from collection2, however I am having issues setting up Optional fields.

I have a simple schema like:

const searchSchema = {
  searchFilter: Optional(String), // this will fail if value is null
  searchFilter: AnyOf(String, null, undefined), // this will work
};

is there any particular reason I get validation error with a null value with Optional(String) ? Am I missing something? Your help would be appreciated as this package is my last hope.

**Comment by jamauro** [comment]
Currently, `Optional` follows the same behavior as Meteor's `Match.Maybe` (see image below)

If you need to send the searchFilter key each time even when its value is `null`, then you can use `AnyOf` like you have in your example. Otherwise you can omit it and use `Optional`. 

Hope that helps.

----

<img width="725" alt="Screenshot 2024-06-18 at 11 52 22 AM" src="https://github.com/jamauro/easy-schema/assets/1749828/c71506e8-9df2-449f-8f0e-c95d5ecfa19e">

**Comment by jamauro** [comment]
I updated the README to add more info on this behavior. I'm not sure I see a reason at this time to change the behavior. If you or someone feels otherwise, feel free to open a discussion.
